In [30]:
import pandas as pd
import pickle

In [7]:
df_equities = pd.read_excel('Datasets/updated3.2_All_Equities_Cleaned.xlsx')
display(df_equities.head())
df_equities.to_csv('Datasets/All_Equities_Cleaned.csv', index=False)

,Dates,KATE US Equity,KBH US Equity,KDP US Equity,KEY US Equity,KEYS US Equity,KHC UW Equity,KIM US Equity,KLAC UQ Equity,KLAC UW Equity,...,CTSH UW Equity,CTVA US Equity,CTXS UQ Equity,CTXS UW Equity,CVC US Equity,CVG US Equity,CVH US Equity,CVS US Equity,CVX US Equity,CXO US Equity
0,1993-01-29,19.8750,8.6875,NaN,16.0625,NaN,NaN,7.3056,3.125,3.125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1993-02-26,17.1875,9.3125,NaN,16.1875,NaN,NaN,7.2778,3.219,3.219,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1993-03-31,18.3750,9.0000,NaN,17.3125,NaN,NaN,7.5833,3.563,3.563,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1993-04-30,17.5000,8.3750,NaN,16.2500,NaN,NaN,7.4444,3.063,3.063,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1993-05-31,16.8125,8.7500,NaN,15.5000,NaN,NaN,6.8889,4.500,4.500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df_equity = pd.read_csv('Datasets/All_Equities_Cleaned.csv', parse_dates=['Dates'])
df_market = pd.read_csv('Datasets/MSCI_Data.csv', parse_dates=['Date'])

In [10]:
display(df_market.head())

,Date,MSCI USA,MSCI USA Value,MSCI USA Low Size,MSCI USA Low Volatility,MSCI USA High Dividend Yield,MSCI USA Quality,MSCI USA Momentum
0,1999-01-29,2673.05,3277.734545,2384.21,995.479542,997.649417,683.831934,512.942863
1,1999-02-26,2598.02,3251.106568,2391.18,969.079546,970.419053,658.588413,500.178311
2,1999-03-31,2705.67,3332.419537,2344.66,989.782505,967.408227,682.563547,528.966699
3,1999-04-30,2802.00,3624.972158,2410.24,1033.753199,1064.030284,688.421002,530.437255
4,1999-05-31,2736.32,3560.597835,2663.08,1024.310711,1045.278656,672.911109,515.715429

In [11]:
print(df_market.info())

<class 'pandas.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date                          325 non-null    datetime64[us]
 1   MSCI USA                      325 non-null    float64
 2   MSCI USA Value                325 non-null    float64
 3   MSCI USA Low Size             325 non-null    float64
 4   MSCI USA Low Volatility       325 non-null    float64
 5   MSCI USA High Dividend Yield  325 non-null    float64
 6   MSCI USA Quality              325 non-null    float64
 7   MSCI USA Momentum             325 non-null    float64
dtypes: datetime64[us](1), float64(7)
memory usage: 20.4 KB
None

In [13]:
df_market['Date'] = df_market['Date'].dt.to_period('M')
df_equity['Dates'] = df_equity['Dates'].dt.to_period('M')

In [15]:
df_market.set_index('Date', inplace=True)
df_equity.set_index('Dates', inplace=True)
df_merged = df_equity.join(df_market, how='inner')
display(df_merged.head())

,KATE US Equity,KBH US Equity,KDP US Equity,KEY US Equity,KEYS US Equity,KHC UW Equity,KIM US Equity,KLAC UQ Equity,KLAC UW Equity,KMB US Equity,...,CVS US Equity,CVX US Equity,CXO US Equity,MSCI USA,MSCI USA Value,MSCI USA Low Size,MSCI USA Low Volatility,MSCI USA High Dividend Yield,MSCI USA Quality,MSCI USA Momentum
Dates,,,,,,,,,,,,,,,,,,,,,
1999-01,19.0938,14.0938,NaN,31.8750,NaN,NaN,13.0000,28.875,28.875,46.9386,...,27.3750,37.2500,NaN,2673.05,3277.734545,2384.21,995.479542,997.649417,683.831934,512.942863
1999-02,16.8438,11.2500,NaN,32.2500,NaN,NaN,12.5833,25.906,25.906,44.5239,...,26.5000,38.4375,NaN,2598.02,3251.106568,2391.18,969.079546,970.419053,658.588413,500.178311
1999-03,16.3125,11.2813,NaN,30.3125,NaN,NaN,12.2917,24.281,24.281,45.1718,...,23.7500,44.3750,NaN,2705.67,3332.419537,2344.66,989.782505,967.408227,682.563547,528.966699
1999-04,16.5313,12.1563,NaN,30.9375,NaN,NaN,13.0833,24.813,24.813,57.7751,...,23.8125,49.8750,NaN,2802.00,3624.972158,2410.24,1033.753199,1064.030284,688.421002,530.437255
1999-05,18.0000,12.0625,NaN,34.7500,NaN,NaN,13.3125,22.750,22.750,55.1838,...,23.0000,46.2500,NaN,2736.32,3560.597835,2663.08,1024.310711,1045.278656,672.911109,515.715429

In [16]:
returns_df = df_merged.pct_change()
display(returns_df.head())

,KATE US Equity,KBH US Equity,KDP US Equity,KEY US Equity,KEYS US Equity,KHC UW Equity,KIM US Equity,KLAC UQ Equity,KLAC UW Equity,KMB US Equity,...,CVS US Equity,CVX US Equity,CXO US Equity,MSCI USA,MSCI USA Value,MSCI USA Low Size,MSCI USA Low Volatility,MSCI USA High Dividend Yield,MSCI USA Quality,MSCI USA Momentum
Dates,,,,,,,,,,,,,,,,,,,,,
1999-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-02,-0.117839,-0.201777,NaN,0.011765,NaN,NaN,-0.032054,-0.102823,-0.102823,-0.051444,...,-0.031963,0.031879,NaN,-0.028069,-0.008124,0.002923,-0.026520,-0.027295,-0.036915,-0.024885
1999-03,-0.031543,0.002782,NaN,-0.060078,NaN,NaN,-0.023174,-0.062727,-0.062727,0.014552,...,-0.103774,0.154472,NaN,0.041435,0.025011,-0.019455,0.021364,-0.003103,0.036404,0.057556
1999-04,0.013413,0.077562,NaN,0.020619,NaN,NaN,0.064401,0.021910,0.021910,0.279008,...,0.002632,0.123944,NaN,0.035603,0.087790,0.027970,0.044425,0.099877,0.008582,0.002780
1999-05,0.088844,-0.007716,NaN,0.123232,NaN,NaN,0.017519,-0.083142,-0.083142,-0.044852,...,-0.034121,-0.072682,NaN,-0.023440,-0.017759,0.104902,-0.009134,-0.017623,-0.022530,-0.027754

In [18]:
print(list(df_market.columns))

['MSCI USA', 'MSCI USA Value', 'MSCI USA Low Size', 'MSCI USA Low Volatility', 'MSCI USA High Dividend Yield', 'MSCI USA Quality', 'MSCI USA Momentum']

In [19]:
targets = list(df_market.columns)

equities = [col for col in returns_df.columns if col not in targets]

#Rolling beta for 5 yrs (60 months)
rolling_var = returns_df[targets].rolling(window=60).var()
all_betas = {}

for equity in equities:
    equity_betas = pd.DataFrame(index=returns_df.index)
    
    for target in targets:
        rolling_cov = returns_df[equity].rolling(window=60).cov(returns_df[target])
        equity_betas[f'Beta_{target}'] = rolling_cov / rolling_var[target]
        
    equity_betas.dropna(inplace=True)
    all_betas[equity] = equity_betas

In [23]:
def clean_key_names(dict_of_dfs):
    cleaned_dict = {}
    for key, df in dict_of_dfs.items():
        cleaned_key = key.split(' ')[0]
        cleaned_dict[cleaned_key] = df
    return cleaned_dict

In [28]:
all_betas_cleaned = clean_key_names(all_betas.copy())
print(all_betas_cleaned.keys())

dict_keys(['KATE', 'KBH', 'KDP', 'KEY', 'KEYS', 'KHC', 'KIM', 'KLAC', 'KMB', 'KMI', 'KMRTQ', 'KMX', 'KO', 'KR', 'KRB', 'KRFT', 'KRI', 'KSE', 'KSS', 'KSU', 'L', 'LDG', 'LDOS', 'LDWIF', 'LEG', 'LEHMQ', 'LEN', 'LHX', 'LIN', 'LKQ', 'LLTC', 'LLY', 'LM', 'LMT', 'LNC', 'LNT', 'LO', 'LOW', 'LPX', 'LRCX', 'LUMN', 'LUV', 'LVLT', 'LVS', 'LW', 'LXK', 'LYB', 'M', 'MA', 'MAA', 'MAC', 'MAR', 'MAS', 'MAT', 'MBI', 'MCD', 'MCHP', 'MCK', 'MCO', 'MDLZ', 'MDP', 'MDRIQ', 'MDT', 'MEE', 'MEL', 'MER', 'MET', 'META', 'MFE', 'MGM', 'MHK', 'MHS', 'MIRKQ', 'MJN', 'MKC', 'MKG', 'MKTX', 'MLM', 'MMM', 'MNKKQ', 'MNST', 'MO', 'MOLX', 'MOS', 'MPC', 'MRK', 'MRO', 'MRSH', 'MS', 'MSCI', 'MSFT', 'MSI', 'MTB', 'MTD', 'MTG', 'MTLQQ', 'MTW', 'MU', 'MUR', 'MWI', 'MWV', 'MWW', 'MXIM', 'MYL', 'MZIAQ', 'NAV', 'NAVI', 'NBL', 'NBR', 'NC', 'NCC', 'NCE', 'NCLH', 'NDAQ', 'NEBLQ', 'NEE', 'NEM', 'NFB', 'NFLX', 'NFX', 'NGH', 'NI', 'NKE', 'NKTR', 'NLSN', 'NMK', 'NOC', 'NOV', 'NOVL', 'NRG', 'NRTLQ', 'NSC', 'NTAP', 'NTRS', 'NUE', 'NVDA', 'NVR', 'NWL', 'NWS', 'NWSA', 'NXTL', 'NYT', 'O', 'OAT', 'OI', 'OK', 'OKE', 'OMC', 'OMX', 'ORCL', 'ORLY', 'ORX', 'OWENQ', 'OXY', 'PALM', 'PARA', 'PAYX', 'PBCT', 'PBG', 'PBI', 'PCAR', 'PCG', 'PCH', 'PCP', 'PDCO', 'PDG', 'PEG', 'PEP', 'PETM', 'PFE', 'PFG', 'PG', 'PGL', 'PGR', 'PH', 'PHM', 'PKG', 'PLD', 'PM', 'PMCS', 'PNC', 'PNR', 'PNW', 'PPG', 'PPL', 'PPW', 'PRDCQ', 'PRGO', 'PRU', 'PSA', 'PSX', 'PTC', 'PTV', 'PVH', 'PVN', 'PWR', 'PXD', 'PYPL', 'QCOM', 'QEP', 'QLGC', 'QRVO', 'QTRN', 'R', 'RADCQ', 'RAI', 'RATL', 'RBD', 'RBK', 'RCL', 'RDC', 'RDPL', 'REG', 'REGN', 'RF', 'RHI', 'RHT', 'RIG', 'RJF', 'RL', 'RMD', 'RML', 'RNB', 'ROH', 'ROK', 'ROL', 'ROP', 'ROST', 'RRC', 'RRD', 'RSG', 'RSHCQ', 'RTN', 'RTX', 'RVTY', 'RX', 'RYC', 'SANM', 'SAPE', 'SBAC', 'SBUX', 'SCG', 'SCHW', 'SCI', 'SEBL', 'SEE', 'SGID', 'SHLDQ', 'SHW', 'SIAL', 'SIG', 'SITC', 'SIVBQ', 'SJM', 'SLB', 'SLG', 'SLM', 'SNA', 'SNPS', 'SNV', 'SO', 'SOV', 'SPG', 'SPGI', 'SRCL', 'SRE', 'SSP', 'STJ', 'STT', 'STX', 'STZ', 'SUNEQ', 'SVU', 'SWK', 'SWKS', 'SWN', 'SWY', 'SXCL', 'SYF', 'SYK', 'SYY', 'T', 'TAP', 'TAP/B', 'TCOMA', 'TDC', 'TDG', 'TEG', 'TER', 'TEX', 'TFC', 'TFCF', 'TFCFA', 'TFX', 'TGNA', 'TGT', 'THC', 'TIE', 'TIN', 'TJX', 'TKR', 'TLAB', 'TMO', 'TMUS', 'TNB', 'TNL', 'TOY', 'TPR', 'TRB', 'TRIP', 'TROW', 'TRV', 'TSCO', 'TSN', 'TSS', 'TT', 'TTWO', 'TUPBQ', 'TWC', 'TWTR', 'TWX', 'TXN', 'TXT', 'TXU', 'UA', 'UAA', 'UAL', 'UAWGQ', 'UCM', 'UDR', 'UHS', 'UIS', 'ULTA', 'UMGI', 'UN', 'UNH', 'UNM', 'UNP', 'UPS', 'URBN', 'URI', 'USB', 'USW', 'V', 'VALPQ', 'VAR', 'VFC', 'VIAB', 'VIAV', 'VLO', 'VMC', 'VNO', 'VRSK', 'VRSN', 'VRTX', 'VSTNQ', 'VTR', 'VTSS', 'VYX', 'VZ', 'WAB', 'WAMUQ', 'WAT', 'WBA', 'WCG', 'WCOEQ', 'WDC', 'WEC', 'WELL', 'WFC', 'WFM', 'WFTIQ', 'WHR', 'WINMQ', 'WLA', 'WM', 'WMB', 'WMT', 'WNDXQ', 'WOR', 'WPX', 'WRK', 'WTW', 'WU', 'WWY', 'WY', 'WYE', 'WYNN', 'X', 'XEC', 'XEL', 'XLNX', 'XOM', 'XRAY', 'XRX', 'XTO', 'XYL', 'YNR', 'YUM', 'ZBH', 'ZION', 'ZTS', 'D', 'DAL', 'DALRQ', 'DCNAQ', 'DD', 'DDS', 'DE', 'DFODQ', 'DFS', 'DG', 'DGX', 'DHI', 'DHR', 'DIS', 'DISCA', 'DISCK', 'DISH', 'DJ', 'DLR', 'DLTR', 'DLX', 'DNRCQ', 'DOC', 'DOFSQ', 'DOV', 'DOW', 'DPHIQ', 'DRE', 'DRI', 'DTE', 'DUK', 'DVA', 'DVN', 'DXC', 'DYNIQ', 'EA', 'EBAY', 'ECL', 'ED', 'EFX', 'EG', 'EHC', 'EIX', 'EKDKQ', 'EL', 'ELV', 'EMN', 'EMR', 'ENDPQ', 'ENRNQ', 'EOG', 'EOP', 'EQIX', 'EQR', 'EQT', 'ES', 'ESRX', 'ESS', 'ETFC', 'ETN', 'ETR', 'EVHC', 'EVRG', 'EW', 'EXC', 'EXPD', 'EXPE', 'EXR', 'F', 'FANG', 'FAST', 'FBF', 'FBIN', 'FCX', 'FDO', 'FDX', 'FE', 'FFIV', 'FHI', 'FHN', 'FIS', 'FISV', 'FITB', 'FJ', 'FL', 'FLIR', 'FLR', 'FLS', 'FLTWQ', 'FMC', 'FMCC', 'FNMA', 'FOSL', 'FOX', 'FOXA', 'FPC', 'FRCB', 'FRT', 'FSH', 'FSL/B', 'FSLR', 'FTI', 'FTLAQ', 'FTNT', 'FTRCQ', 'FTV', 'FWLT', 'GAP', 'GAPTQ', 'GAS', 'GBLXQ', 'GD', 'GDW', 'GE', 'GEN', 'GENZ', 'GGP', 'GHC', 'GILD', 'GIS', 'GL', 'GLW', 'GM', 'GMCR', 'GME', 'GNW', 'GOOG', 'GOOGL', 'GPC', 'GPN', 'GPUI', 'GR', 'GRA', 'GRMN', 'GS', 'GT', 'GTW', 'GWW', 'HAL', 'HAR', 'HAS', 'HBAN', 'HBI', 'HCA', 'HCBK', 'HD', 'HES', 'HET', 'HFC', 'HIG', 'HII', 'HLT', 'HM', 'HNZ', 'HOG', 'HOLX', 'HON', 'HOT', 'HP', 'HPC', 'HPE', 'HPQ', 'HRB', 'HRL', 'HRZIQ', 'HSH', 'HSIC', 'HSP', 'HST', 'HSY', 'HUM', 'HWM', 'IBM', 'ICE', 'IDXX', 'IEX', 'IFF', 'IKN', 'ILMN', 'IMNX', 'INCLF', 'INCY', 'INTC', 'INTU', 'IP', 'IPG', 'IPGP', 'IQV', 'IRM', 'ISRG', 'IT', 'ITT', 'ITW', 'IVZ', 'JBHT', 'JBL', 'JCI', 'JEF', 'JHF', 'JKHY', 'JNJ', 'JNPR', 'JNS', 'JNY', 'JOSEA', 'JOY', 'JPM', 'JWN', '0111145D', '0202445Q', '0203524D', '0226226D', '0544749D', '0574018D', '0772031D', '0820143D', '0848680D', '0867887D', '0872237D', '0910150D', '0948669D', '0961514D', '0964591D', '1028411Q', '1040983D', '1051665D', '1086832D', '1255173D', '1255177D', '1255459D', '1280712D', '1281683D', '1284849D', '1288453D', '1288652D', '1293405D', '1312089D', '1317355D', '140402Q', '1431816D', '1436513D', '1448062D', '1500785D', '1518855D', '1519128D', '1520415D', '1524867D', '1528159D', '1539941D', '1541931D', '1566019D', '1621582D', '1627457D', '1649858D', '1654539D', '1683351D', '1683997D', '1684442D', '1697067D', '1703561D', '1704453D', '1715651D', '1719868D', '1727044D', '1746513D', '1752754D', '1778808D', '1789494D', '1799685D', '1806854D', '1810430D', '1812212D', '1822785D', '1825471D', '1831877D', '183291Q', '1837572D', '1856613D', '1858968D', '1916672D', '1920486D', '1922150D', '1927294D', '1972693D', '1996074D', '1996760D', '2071296D', '2073714D', '2078185D', '2207158D', '2213185D', '2217347D', '222435Q', '2258717D', '2269312Q', '228510Q', '2288005Q', '2307532Q', '2326007D', '2326248D', '236555Q', '2370058D', '244630Q', '2454227D', '2481644D', '2499073D', '2502261D', '253647Q', '2544554D', '2557974D', '2558202D', '2567699D', '2572102D', '2572350D', '2584271D', '2596482D', '2596516D', '2613148D', '2616271D', '2619871D', '2621018D', '2622092D', '2641504Q', '2676187Q', '2691Q', '2727195Q', '2731112Q', '2745Q', '2755Q', '2770014Q', '285939Q', '291784Q', '2942331Q', '2953349Q', '2968900Q', '2972Q', '297504Q', '2987536Q', '2999130Q', '300583Q', '301710Q', '3022239Q', '3026360Q', '3029830Q', '304024Q', '3054Q', '3075558Q', '3080867Q', '3133754Q', '3153670Q', '3179Q', '3253Q', '3277Q', '3286728Q', '329556Q', '3301Q', '3346Q', '3362726Q', '3393199Q', '3403545Q', '3414924Q', '3423152Q', '3459Q', '3517233Q', '3546Q', '355488Q', '3605818Q', '3621240Q', '363096Q', '3692470Q', '375573Q', '3891289Q', '390297Q', '399463Q', '41018Q', '45200Q', '4621824Q', '502466Q', '519239Q', '544791Q', '548227Q', '5656565D', '571300Q', '605018Q', '605555Q', '611647Q', '653707Q', '667517Q', '677004Q', '680884Q', '68335Q', '723588Q', '739306Q', '748957Q', '764144Q', '8206908Q', '8214761Q', '827663Q', '8277831Q', '8394653Q', '841273Q', '89236Q', '896661Q', '929530Q', '93916Q', '945852Q', '950967Q', '968734Q', '987200Q', '9876544D', '9876549D', '9876566D', '9903115D', '9980328D', '9983490D', '9990213D', '9990253D', '9991429D', 'A', 'AA', '9995522D', 'AAPL', 'ABBV', 'ABKFQ', 'ABMD', 'ABT', 'ACAS', 'ACKH', 'ACN', 'ADBE', 'ADI', 'ADM', 'ADP', 'ADSK', 'AEE', 'AEP', 'AES', 'AET', 'AFL', 'AFS', 'AGN', 'AIG', 'AIV', 'AIZ', 'AJG', 'AKAM', 'AKS', 'ALB', 'ALGN', 'ALK', 'ALL', 'ALLE', 'ALXN', 'AMAT', 'AMCC', 'AMCR', 'AMD', 'AME', 'AMG', 'AMGN', 'AMP', 'AMT', 'AMZN', 'AN', 'ANDV', 'ANDW', 'ANET', 'ANF', 'ANRZQ', 'ANSS', 'AON', 'AOS', 'APA', 'APD', 'APH', 'APOL', 'ARE', 'ARG', 'ASH', 'ATGE', 'ATI', 'ATO', 'ATVI', 'AVB', 'AVGO', 'AVP', 'AVY', 'AW', 'AWE', 'AWK', 'AXP', 'AYE', 'AYI', 'AZA', 'AZO', 'B', 'BA', 'BAC', 'BALL', 'BAX', 'BBBYQ', 'BBWI', 'BBY', 'BC', 'BCR', 'BDK', 'BDX', 'BEN', 'BF/B', 'BFH', 'BGEN', 'BGGSQ', 'BHF', 'BHI', 'BHMSQ', 'BIGGQ', 'BIIB', 'BK', 'BKB', 'BKNG', 'BKR', 'BLS', 'BMC', 'BMG', 'BMS', 'BMY', 'BNI', 'BOL', 'BR', 'BRCM', 'BRK/B', 'BRL', 'BSX', 'BTUUQ', 'BWA', 'BXLT', 'BXP', 'C', 'CAG', 'CAH', 'CAR', 'CAT', 'CB', 'CBE', 'CBOE', 'CBRE', 'CCEP', 'CCI', 'CCK', 'CCL', 'CCTYQ', 'CDNS', 'CDW', 'CE', 'CELG', 'CEPH', 'CERN', 'CF', 'CFC', 'CFG', 'CFN', 'CGP', 'CHD', 'CHKAQ', 'CHRW', 'CHTR', 'CI', 'CIEN', 'CIN', 'CINF', 'CITGQ', 'CL', 'CLF', 'CLX', 'CMA', 'CMCSA', 'CMCSK', 'CME', 'CMG', 'CMI', 'CMS', 'CMVT', 'CMX', 'CNC', 'CNCEQ', 'CNP', 'CNX', 'COF', 'COL', 'COO', 'COP', 'COR', 'COST', 'COTY', 'COV', 'CPAY', 'CPB', 'CPGX', 'CPNLQ', 'CPPRQ', 'CPRI', 'CPRT', 'CRM', 'CSCO', 'CSRA', 'CSX', 'CTAS', 'CTB', 'CTRA', 'CTSH', 'CTVA', 'CTXS', 'CVC', 'CVG', 'CVH', 'CVS', 'CVX', 'CXO'])

In [29]:
display(all_betas_cleaned['AAPL'].head())

,Beta_MSCI USA,Beta_MSCI USA Value,Beta_MSCI USA Low Size,Beta_MSCI USA Low Volatility,Beta_MSCI USA High Dividend Yield,Beta_MSCI USA Quality,Beta_MSCI USA Momentum
Dates,,,,,,,
2004-01,1.747060,1.172146,-0.161913,1.334105,0.133319,1.810972,1.727158
2004-02,1.724819,1.164057,-0.159184,1.289467,0.093293,1.781436,1.703704
2004-03,1.727779,1.153255,-0.151090,1.286026,0.074824,1.779526,1.728418
2004-04,1.681821,1.060692,-0.180637,1.178646,-0.158002,1.749081,1.723620
2004-05,1.682972,1.058989,-0.165065,1.179066,-0.168291,1.746328,1.727109

In [31]:
with open('Datasets/all_betas_cleaned.pkl', 'wb') as f:
    pickle.dump(all_betas_cleaned, f)